### DISCUSSION TITLE
I can't connect to an MQTT broker running on Docker with a Node application

### DISCUSSION THREAD

**Discussion by nicola907** [mqttjs/MQTT.js#1803] [General]
I have an MQTT broker running on a docker container:

    mqtt-broker:
        image: rabbitmq
        container_name: mqtt-broker
        ports:
            - "1883:1883"
            - "9001:9001"

I want to create a Node client running on the host machine, but I can't make it connect to the broker. Here is my code:

    const mqtt = require('mqtt');
    const brokerUrl = 'mqtt://localhost:1883';
    const topic = 'myTopic';
    
    const client = mqtt.connect(brokerUrl, {
        protocol: 'tcp'
    });
    
    client.on('error', (err) => {
        console.error('Error:', err);
    });
    
    client.on('connect', () => {
        console.log('Connected to MQTT broker');
        client.subscribe(topic, (err) => {
            if (err) {
                console.error('Error subscribing to topic:', err);
            } else {
                console.log('Subscribed to topic:', topic);
            }
        });
    });

Here is what I get:

    Error: Error: read ECONNRESET
        at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
      errno: -104,
      code: 'ECONNRESET',
      syscall: 'read'
    }

I tried to set the brokerUrl variables to other values such as 'mqtt://localhost:9001', 'mqtt://mqtt-broker:9001', 'mqtt://mqtt-broker:1883' but it has never worked. The "mqtt-broker" container is running without errors.

**Comment by robertsLando** [comment]
I think you should double check your rabbitmq.conf and ensure to have `mqtt.listeners.tcp.default = 1883`.  Another try you can do is to use `network_mode: host` in your docker compose like this:

```yml
mqtt-broker:
    image: rabbitmq
    container_name: mqtt-broker
    network_mode: host
```

If it works it means the problem is the container ports are not accessible from localhost for some reasons. For sure this is not an MQTTjs related issue BTW

**Reply by nicola907** [reply]
Apparently the RabbitMQ Docker image doesn't include a default "rabbitmq.conf" file, therefore I tried to set `mqtt.listeners.tcp.default = 1883` through the `docker-compose.yml` file. Since it didn't work I also tried to add `network_mode: host`, but it didn't work either.

  ```
mqtt-broker:
    image: rabbitmq
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit mqtt.listeners.tcp.default 1883"
    network_mode: host
```
